language: ruby
rvm:
- "2.2.2"
env: COVERAGE=true DB=mysql RAILS_ENV=test
install: 'bundle install'
before_script: 
  - mysql -e 'create database enviroconnect_test'
script:
  - mv config/travis-db.yml config/database.yml
  - bundle exec rake --trace db:migrate test
sudo: false
notifications:
  email: false
